language: node_js
node_js:
- "9"

deploy:
  provider: script
  script: "cp .npmrc.template $HOME/.npmrc && npm publish"
  skip_cleanup: true
  on:
    tags: true

after_success: npm run prod

notifications:
  email:
    recipients:
    - tomasrsduarte@gmail.com
    on_success: change
    on_failure: always